---
linters:
  enable-all: true
  disable:
    - wsl
    - err113
    - lll
    - godot
    - nlreturn
    - godox
    - tagliatelle
    - ireturn
    - varnamelen
    - exhaustruct
    - depguard
    - tenv # WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting.
