---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
    - .github/workflows/test-release.yaml
    - .goreleaser.yml
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: '1.24.2'

    - name: Run GoReleaser (skip publish)
      uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
      if: "! startsWith(github.ref, 'refs/tags/')"
      with:
        version: latest
        args: release --clean --snapshot
