---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
    - .github/workflows/test-release.yaml
    - .goreleaser.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.17'

    - name: Run GoReleaser (skip publish)
      uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v3.2.0
      if: "! startsWith(github.ref, 'refs/tags/')"
      with:
        version: latest
        args: release --clean --snapshot
