---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
    - .github/workflows/test-release.yaml
    - .goreleaser.yml
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.23.2'

    - name: Run GoReleaser (skip publish)
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
      if: "! startsWith(github.ref, 'refs/tags/')"
      with:
        version: latest
        args: release --clean --snapshot
