---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@fbe492a9fd564e62fab528f0f60a7332120056d5 # v3.2.2
    with:
      aqua_version: v2.53.8
    permissions:
      pull-requests: write
      contents: read
