---
name: wc-test
on: workflow_call
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@7fc75812b57545fe85aaa397f3dd899d4b89241b # v3.2.0
    with:
      aqua_version: v2.48.1
    permissions:
      pull-requests: write
      contents: read
