---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@05399afd417ae28382877ebe5bf7c9288b023df7 # v3.2.1
    with:
      aqua_version: v2.51.1
    permissions:
      pull-requests: write
      contents: read
