---
name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@10238675cfaeb021a013ac656c58babe6ff69a62 # v5.0.0
    with:
      aqua_version: v2.55.1
    permissions:
      pull-requests: write
      contents: read
